export let navList = [
  {
    name: "Pricing",
    href: "/",
  },
  {
    name: "Client Area",
    href: "/client",
  },
];

export const Plans = [
  "Budget Residential",
  "Premium Residential",
  "Premium LTE",
  "Mobile LTE",
];

export let countries = [
  "Random",
  "UnitedStates",
  "Canada",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Belarus",
  "Belgium",
  "BosniaandHerzegovina",
  "Brazil",
  "BritishVirginIslands",
  "Brunei",
  "Bulgaria",
  "Cambodia",
  "Cameroon",
  "Chile",
  "China",
  "Colombia",
  "CostaRica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Denmark",
  "DominicanRepublic",
  "Ecuador",
  "Egypt",
  "ElSalvador",
  "Estonia",
  "Ethiopia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Guatemala",
  "Guyana",
  "HashemiteKingdomofJordan",
  "HongKong",
  "Hungary",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Kazakhstan",
  "Kenya",
  "Kosovo",
  "Kuwait",
  "Latvia",
  "Liechtenstein",
  "Luxembourg",
  "Macedonia",
  "Madagascar",
  "Malaysia",
  "Mauritius",
  "Mexico",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Nepal",
  "Netherlands",
  "NewZealand",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestine",
  "Panama",
  "PapuaNewGuinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "PuertoRico",
  "Qatar",
  "RepublicofLithuania",
  "RepublicofMoldova",
  "Romania",
  "Russia",
  "SaudiArabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Somalia",
  "SouthAfrica",
  "SouthKorea",
  "Spain",
  "SriLanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Thailand",
  "TrinidadandTobago",
  "Tunisia",
  "Turkey",
  "Uganda",
  "Ukraine",
  "UnitedArabEmirates",
  "UnitedKingdom",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Zambia",
];

let Mobile_LTE_Features = [
  "ATT ISP",
  "Unlimited Threads",
  "Rotation once per 30 minutes",
  "Only IP Auth",
  "USA IPs",
  "One port, which rotates ip every 30 minutes",
];
export const Mobile_LTE_Data = [
  {
    price: 6,
    size: 1,
    note: "Per 1 Day of access",
    features: Mobile_LTE_Features,
  },
  {
    price: 35,
    size: 7,
    note: "Per 1 Week of access",
    features: Mobile_LTE_Features,
  },
];

let Residential_Features = [
  "20.000.000+ IP Pool",
  "Unlimited Threads",
  "Premium Support",
  "Only user:pass auth",
  "Country/State/City Targetting Available",
  "Rotating/Sticky Sessions",
];

export const Residential_Data = [
  {
    price: 5,
    size: 1,
    note: "Per 1 GB of data",
    features: Residential_Features,
  },
  {
    price: 10,
    size: 2,
    note: "Per 2 GB of data",
    features: Residential_Features,
  },
  {
    price: 24,
    size: 5,
    note: "Per 5 GB of data",
    features: Residential_Features,
  },
  {
    price: 110,
    size: 25,
    note: "Per 25 GB of data",
    features: Residential_Features,
  },
];
